name    'erwbgy-activemq'
version '0.1.0'
source 'https://github.com/erwbgy/puppet-activemq.git'
author 'erwbgy'
license 'Apache License, Version 2.0'
summary 'Run ActiveMQ instances under Runit'
description 'Run ActiveMQ instances under Runit'
project_page 'http://forge.puppetlabs.com/erwbgy/activemq'
dependency 'erwbgy/runit', '>= 0.4.1'
